"""add invitation configuration key

Revision ID: 1279057ff8ea
Revises: 1a8e2103177c
Create Date: 2026-10-05 01:54:41.671288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1279057ff8ea'
down_revision: Union[str, Sequence[str], None] = '1a8e2103177c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation_codes', sa.Column('configuration_key', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation_codes', 'configuration_key')
    # ### end Alembic commands ###
