"""link users to base configurations

Revision ID: 9d75e2ca6019
Revises: 1279057ff8ea
Create Date: 2026-10-05 02:13:16.859475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d75e2ca6019'
down_revision: Union[str, Sequence[str], None] = '1279057ff8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('base_configuration_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'base_configurations', ['base_configuration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'base_configuration_id')
    # ### end Alembic commands ###
